### ISSUE TITLE
演示图片不要

### ISSUE THREAD

**Issue by sonichy** [xiaoyanLG/Qt_Gif_Creator#1]
演示图片没啥意义，而且太大了，不要放在源码里面，实在需要可以放到图床。
引用别人的代码需要注明出处（方便别人抄丫 (*^__^*) ）

**Comment by xiaoyanLG** [comment]
演示图片为什么没有意义？ 告诉别人编译出来的是个什么东西，我觉得非常必要(这样可以看是否是自己想要的东西)。另外。gif的源码来源的话，恐怕也不好找真正的来处了，你可以看那个文件里面的描述去找出处就行了。

**Comment by sonichy** [comment]
程序UI给一张图就行了。
鼠标穿透的原理是什么？
